### ISSUE TITLE
tsintermittent no longer on CRAN

### ISSUE THREAD

**Issue by stegerj** [trnnick/tsintermittent#3]
CRAN removed the tsintermittent package since end of April 22. Kindly asking if you planned to dismiss it or continue maintaining it. Thanks for your work!

**Comment by trnnick** [comment]
I am in the process of updating it, a new version should be submitted on CRAN in the following days. 
Thanks for the heads up and for finding this useful!

**Comment by trnnick** [comment]
Updated, on its way to CRAN
